### ISSUE TITLE
specific features

### ISSUE THREAD

**Issue by cirrusflyer** [cdalar/onctl#486]
Nice work @cdalar 

On Hetzner, I noticed the VMs are defaulting to Ubuntu 22.04 LTS.  Is there a way to specify the OS?  And can we also specify a Hetzner firewall and internal network?

Thanks

**Comment by cirrusflyer** [comment]
The OS change is working.  Thanks!

But I noticed with 24.04 and running a cloudinit and a template, the "waiting for VM" times out.  Can the time be extended?  I know there a lot of updates to install.

Something like this:

onctl up -i test2.config -a docker.sh

test2.config is:

#cloud-config
package_update: true
package_upgrade: true

**Comment by cdalar** [comment]
@cirrusflyer thanks for the issues you mention. 

Just created a new release. v0.1.16 ..that should fix your timeout problem. About the networking, currently working on it. Can not give you an estimate at the moment. And for the firewalls, not planned at the moment.

**Comment by cirrusflyer** [comment]
Thanks!  I've already installed and tested and seems to be working fine.
